from typing import Protocol, Dict, Any, List

class ICardApp(Protocol):
    """Interface for CardApp functionality needed by UIComponents"""
    def display_card_info(self, card: Dict[str, Any]) -> None: ...
    def save_collection(self) -> None: ...
    
    @property
    def cards(self) -> List[Dict[str, Any]]: ...
    @cards.setter
    def cards(self, value: List[Dict[str, Any]]) -> None: ...
    
    @property
    def collection(self) -> Dict[str, Any]: ...
    @collection.setter
    def collection(self, value: Dict[str, Any]) -> None: ...